name: 'Set package.json version environment variable'

description: 'Sets the current npm package version in a workflow'

runs:
  using: 'composite'
  steps:
    - run: |
        echo PACKAGE_VERSION=`node -p "require('./package.json').version"` >> $GITHUB_ENV
      shell: bash
